# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTC001():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_tC001(self):
        self.driver.get("https://www.google.com/")
        self.driver.set_window_size(984, 680)
        self.driver.find_element(By.ID, "APjFqb").send_keys("Testing")
        self.driver.find_element(By.CSS_SELECTOR, "form > div:nth-child(1)").click()
        self.driver.find_element(By.CSS_SELECTOR, "center:nth-child(1) > .gNO89b").click()
        self.driver.find_element(By.ID, "_4JeBacvTL7GRseMPtfuKkAo_229").click()
        elements = self.driver.find_elements(By.CSS_SELECTOR, "p:nth-child(7)")
        assert len(elements) > 0

